/**
 * Network Manager territory licence flow constants.
 * Amounts in pence (smallest unit) where applicable.
 */

const RESERVATION_TTL_MINUTES = 10;
const LICENCE_FEE_DEFAULT_PENCE = 250000; // £2,500
const CONTRACT_DURATION_MONTHS = 12;

const UI_STATUS = {
  AVAILABLE: "AVAILABLE",
  WAITLIST: "WAITLIST",
  LOCKED: "LOCKED",
};

const TERRITORY_STATUS = {
  ACTIVE: "ACTIVE",
  LOCKED: "LOCKED",
  UPCOMING: "UPCOMING",
  DISABLED: "DISABLED",
};

const RESERVATION_STATUS = {
  HELD: "HELD",
  RELEASED: "RELEASED",
  CONVERTED: "CONVERTED",
  EXPIRED: "EXPIRED",
};

const LICENCE_STATUS = {
  PENDING_APPROVAL: "PENDING_APPROVAL",
  ACTIVE: "ACTIVE",
  EXPIRED: "EXPIRED",
  SUSPENDED: "SUSPENDED",
  CLEARED: "CLEARED",
};

const PAYMENT_MODE = {
  PAY_NOW: "PAY_NOW",
  CLEAR_FROM_EARNINGS: "CLEAR_FROM_EARNINGS",
};

const SERVICE_FEE_RATE_UNCLEARED = 0.2;   // 20%
const SERVICE_FEE_RATE_CLEARED = 0.15;    // 15%
const SERVICE_FEE_RATE_LEVEL3 = 0.1;      // 10%

/** Licences that hold a slot (count toward max_slots) */
const LICENCE_STATUSES_HOLDING_SLOT = ["ACTIVE", "CLEARED"];

const LEVEL_STATUS = { L1: "L1", L2: "L2", L3: "L3" };

module.exports = {
  LEVEL_STATUS,
  LICENCE_STATUSES_HOLDING_SLOT,
  RESERVATION_TTL_MINUTES,
  LICENCE_FEE_DEFAULT_PENCE,
  CONTRACT_DURATION_MONTHS,
  UI_STATUS,
  TERRITORY_STATUS,
  RESERVATION_STATUS,
  LICENCE_STATUS,
  PAYMENT_MODE,
  SERVICE_FEE_RATE_UNCLEARED,
  SERVICE_FEE_RATE_CLEARED,
  SERVICE_FEE_RATE_LEVEL3,
};
